version: "3.9"

services:
  minio:
    container_name: minio
    image: bitnami/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - s3-data:/data

volumes:
  s3-data: {}

networks:
  default:
    name: minio-network