version: "3.9"

services:
  minio:
    container_name: minio
    image: bitnami/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - s3-data:/data

volumes:
  s3-data: {}

networks:
  default:
    name: minio-network