---
version: "3.9"

services:
  caddy:
    image: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      #- $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data: {}
    # external: true
  caddy_config: {}

networks:
  default:
    name: ical2web-network

...